### ISSUE TITLE
Investigate adding FreeBSD to CI

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1311]
spectest failures in #1307 went unnoticed, it'd be good to test on FreeBSD too as long as it's not unreasonably hard or slow to do so

**Comment by syrusakbary** [comment]
I took a look few months ago, unfortunately FreeBSD is not supported by our current CI (Azure Pipelines).

Let's keep the issue open until we figure a way to integrate CI on FreeBSD

**Comment by MikaelUrankar** [comment]
Is it possible to use cirrus? It supports FreeBSD (here is an example, cirrus.yml):
```
freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  timeout_in: 90m
  install_script:
  - pkg install -y rust-nightly
  script:
  - make spectests-singlepass
```
