### ISSUE TITLE
How to run a WASI module that needs a memory import?

### ISSUE THREAD

**Issue by roee88** [wasmerio/wasmer#2519]
### Summary

It seems like it's impossible to run a WASI module that expects the memory to be imported. Is that by design and a limitation of WASI itself or an issue with WASI support in wasmer?

### Additional details

I created a wasm32-wasi module in rust by passing the  `--import-memory` argument to lld. The resulting wasm-wasi module includes an import from env.memory and it doesn't include a memory export (there is no way to do both in llvm).

I then tried to run the module with wasmer (rust) but it fails because it fails to find a memory _export_.  The main issue I think is that it expects memory to be exported due to the annotation in https://github.com/wasmerio/wasmer/blob/519a403b3e3ae4efab188d518ec2c58886916fca/lib/wasi/src/lib.rs#L59-L60.

Without wasi, wasmer works with modules that import memory by giving an import object with env memory. However, with wasi even if you chain your own import object that has a memory import to the wasienv import object it doesn't work. Probably because the code linked above is hard coded only for modules that export memory.

**Comment by syrusakbary** [comment]
That's a use case we didn't foresee when checking WASI imports, but I believe it should be easy to add support to it.

Could you attach the generated wasm so we can take a look at the expected name of the import?

**Comment by roee88** [comment]
I compiled an "hello world" module with the following `.cargo/config.toml`:
```toml
[target.wasm32-wasi]
rustflags = [
  "-C", "link-args=--import-memory",
]
```

The result of `wasmer inspect` on the compiled module is:

```
Type: wasm
Size: 1.4 MB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."proc_exit": [I32] -> []
    "wasi_snapshot_preview1"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_get": [I32, I32] -> [I32]
  Memories:
    "env"."memory": not shared (17 pages..)
  Tables:
  Globals:
Exports:
  Functions:
    "_start": [] -> []
  Memories:
  Tables:
  Globals:
    "__heap_base": I32 (constant)
    "__data_end": I32 (constant)
```
