### ISSUE TITLE
Support multiple LLVM versions in Wasmer.

### ISSUE THREAD

**Issue by wchaudry** [wasmerio/wasmer#2651]
Currently Wasmer ships with LLVM 11. We will support multiple versions of LLVM based on user configuration as a new feature.

**Comment by Kiuhrly** [comment]
It looks like Inkwell supports this via feature flags: https://github.com/TheDan64/inkwell#usage

But in wasmer_compiler_llvm, it's hardcoded to `llvm14-0` [here](https://github.com/wasmerio/wasmer/blob/296061f203594eec3c1128785238039c0a030ad0/lib/compiler-llvm/Cargo.toml#L32):

```toml
[dependencies.inkwell]
package = "inkwell"
version = "0.1.1"
default-features = false
features = ["llvm14-0", "target-x86", "target-aarch64"]
```

Maybe this could be exposed via feature flags in wasmer?
