### ISSUE TITLE
Wasmer-WASI depends on Cranelift by default

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#2882]
When using the Wasmer-WASI crate, the `sys-default` feature from `wasmer` is depending upon, which causes the following to conflict

```toml
wasmer = { version = "2.0", default-features=false,  features=["sys" , "compiler-singlepass", "engine-universal"] }
wasmer-wasi = "2.0"
```

(because wasmer-wasi "2.0" depends on wasmer with the default features, which implies using cranelift, which conflicts with singlepass)
