### ISSUE TITLE
WASM file detected as invalid because bulk memory support is not enabled

### ISSUE THREAD

**Issue by k33g** [wasmerio/wasmer#3932]
### Summary

Hello,
I build a wasm module with TinyGo like this:
```bash
tinygo build -o hello-orange.wasm \
    -scheduler=none \
    --no-debug \
    -target wasi ./main.go 
```

I would like to publish it to https://wapm.io/, but when I try this command `wapm publish`, I get this error message:

```bash
Error: WASM file "hello-orange.wasm" detected as invalid because bulk memory support is not enabled (at offset 3196)
```

I created an [issue](https://github.com/tinygo-org/tinygo/issues/3758) on the TinyGo project, but I wanted to know if I forgot something in `wapm.toml`? Thank you 🙏

### Additional details

> `wapm.toml`
```toml
[package]
name = "k33g/hello-orange"
version = "1.0.0"
description = "Package description for k33g/hello-orange"
license = "MIT"

[[module]]
name = "hello-orange"
source = "hello-orange.wasm"
abi = "wasi"
```
