### ISSUE TITLE
Mapped dirs in the fs section don't show in listdir

### ISSUE THREAD

**Issue by dynamite-bud** [wasmerio/wasmer#4255]
## Description
When mapping directories in a manifest file, all the directories don't show in the listdir.

## Found Where?

Found when trying to use a python script in WASIX

### Setup a python worker

1. Select the python worker in `wasmer app create`

```shell
$ wasmer app create
> Python Worker
```

> This will create a basic http server

The `wasmer.toml` looks like this

```toml
# ...
[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/src/main.py"]
```

As we see the `/src` is mapped to the host's src directory.

### Print the list of directories in current directory

Add the following lines in `src/main.py`:
```
if __name__ == "__main__":
    print(os.getcwd()) # <- Added here
    print(os.listdir('.')) <- Added here
    host = os.environ.get('HOST', '127.0.0.1')
```

Once that's done try to run it.

### Running the python server

```sh
$ wasmer run . --net --env PORT=4000
/
['.app', '.private', 'bin', 'cpython', 'dev', 'etc', 'tmp']
Starting server on http://127.0.0.1:4000
```

The output as seen above doesn't show the `src` directory anywhere.
