### ISSUE TITLE
`realloc is not a function` when using tinygo

### ISSUE THREAD

**Issue by SadraMoh** [wasmerio/wasmer#4310]
### Describe the bug

When trying to use a `wasi` library that was compiled using `tinygo` within `nodejs`, through the bindings provided by wasmer, I get the error that the identifier `realloc` is undefined. This happens when calling an exported function in the package.

```js
const mod = await goBindings.universal_lib_go();
mod.hello('from Go');
```

```node
ptr = realloc(ptr, alloc_len, 1, alloc_len + s.length);
      ^

TypeError: realloc is not a function
    at utf8_encode (/home/sadramoh/code/workshop/backend/soup/node_modules/@sadramoh/universal_lib_go/src/bindings/universal-lib-go/intrinsics.js:24:11)
    at UniversalLibGo.hello (/home/sadramoh/code/workshop/backend/soup/node_modules/@sadramoh/universal_lib_go/src/bindings/universal-lib-go/universal-lib-go.js:27:18)
    at file:///home/sadramoh/code/workshop/backend/soup/index.js:24:16
```

```sh
$ wasmer -vV; tinygo version
wasmer 4.2.3 (7cb550d 2023-10-27)
binary: wasmer-cli
commit-hash: 7cb550db60656352cc527eaf869981d39448e38d
commit-date: 2023-10-27
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift,llvm
tinygo version 0.30.0 linux/amd64 (using go version go1.21.4 and LLVM version 16.0.1)
```

### Steps to reproduce

- Clone the following [repo ](https://github.com/SadraMoh/web-assembly-workshop)  on branch `undefined-realloc`

or

- Create the following folder structure: 

```
├── go.mod
├── main.go
├── universal-lib-go.wai
└── wasmer.toml
```

main.go:
```go
package main

import "fmt"

//go:wasm-module yourmodulename
//export hello
func hello(name string) string {
	greeting := fmt.Sprintf("Hello, %s!", name)
  return greeting
}

// main is required for the `wasi` target, even if it isn't used.
func main() {}
```
universal-lib-go.wai:
```wai
// say hello to the user
hello: func(user: string) -> string
```
wasmer.toml:
```toml
[package]
name = "<namespace>/universal_lib_go"
version = "0.0.1-alpha.1"
description = "Universal go library"

[[module]]
name = "universal_lib_go"
source = "universal_lib_go.wasm"
abi = "wasi"

[module.bindings]
wai-version = "0.1.0"
exports = "universal-lib-go.wai"
```

- Build and publish the library to `wasmer.io`
- Create a node project with package `"type": "module"`
- Install the library using npm
- Run the index.js file with the following content:

```js
import { bindings as goBindings } from '@<namespace>/universal_lib_go';

const mod = await goBindings.universal_lib_go();
const res = mod.hello('from Go');

console.log(res);
```

### Expected behavior
The string "Hello from Go!" is printed to the console.

### Actual behavior
App crashes with the `TypeError` mentioned above.

### Additional context
OS: WSL2 Ubuntu on win11
