### ISSUE TITLE
CLI: wasmer deploy: existing app not detected properly when no namespace specified

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4957]
When running `wasmer deploy` with the below app config, the command prompts for chosing the owner, even though the app already exists and has an owner. An app id is present in the config.

Correct behaviour: do not prompt for an owner, just detect that the app already exists and deploy.

```yaml
kind: wasmer.io/App.v0
name: wasmer-tests-js-worker-basic
app_id: da_zRLmILtvUyj2
package: wasmer-tests/js-worker-basic
cli_args:
  - /src/index.js
  ```
