### ISSUE TITLE
@wasmer/bash not respected parameters

### ISSUE THREAD

**Issue by oritwoen** [wasmerio/wasmer#5473]
### Describe the bug

I this command:
```toml
[[command]]
name = "install"
runner = "wasi"
module = "wasmer/bash:bash"
[command.annotations.wasi]
main-args = ["/app/wp-install.sh"]
```

**wp-install.sh:**
```bash
...
rm -rf /app/wp-content/themes
...
```

I got error

```
rm: cannot remove '/app/wp-content/themes': Directory not empty (os error 55)
```
